services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    entrypoint: >
      bash -c "
      echo 'Forcefully killing any existing realtime analyzer processes...' &&
      pkill -9 -f 'src/services/realtime_analyzer.py' || true &&
      pkill -9 -f 'python -m src.services.realtime_analyzer' || true &&
      sleep 1 &&
      echo 'Creating empty metrics file...' &&
      mkdir -p /app/data/outputs &&
      echo '[]' > /app/data/outputs/realtime_metrics.json &&
      chmod 666 /app/data/outputs/realtime_metrics.json &&
      echo 'Starting Streamlit app...' &&
      streamlit run src/web/app.py --server.address=0.0.0.0
      "

  agent:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python src/agents/run_agent.py
    entrypoint: >
      bash -c "
      echo 'Forcefully killing any existing realtime analyzer processes...' &&
      pkill -9 -f 'src/services/realtime_analyzer.py' || true &&
      pkill -9 -f 'python -m src.services.realtime_analyzer' || true &&
      sleep 1 &&
      echo 'Creating empty metrics file...' &&
      mkdir -p /app/data/outputs &&
      echo '[]' > /app/data/outputs/realtime_metrics.json &&
      chmod 666 /app/data/outputs/realtime_metrics.json &&
      echo 'Starting agent...' &&
      python src/agents/run_agent.py
      "

  realtime-analyzer:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m src.services.realtime_analyzer
    entrypoint: >
      bash -c "
      echo 'Setting up environment for realtime analyzer...' &&
      mkdir -p /app/data/outputs &&
      if [ -f /app/data/outputs/realtime_metrics.json ]; then
        chmod 666 /app/data/outputs/realtime_metrics.json
      else
        echo '[]' > /app/data/outputs/realtime_metrics.json &&
        chmod 666 /app/data/outputs/realtime_metrics.json
      fi &&
      echo 'Starting realtime analyzer...' &&
      python -m src.services.realtime_analyzer
      "

  main:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python scripts/main.py data/raw/rapport.json
    entrypoint: >
      bash -c "
      mkdir -p /app/data/raw &&
      python scripts/main.py data/raw/rapport.json
      "

  analyzer:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m src.core.analyzer data/raw/rapport.json
    entrypoint: >
      bash -c "
      mkdir -p /app/data/raw &&
      python -m src.core.analyzer data/raw/rapport.json
      "

  analyze-realtime:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: python -m src.services.analyze_realtime
    entrypoint: >
      bash -c "
      mkdir -p /app/data/outputs &&
      python -m src.services.analyze_realtime
      " 